### PR TITLE
write queue - filesystem notifications

### PR DESCRIPTION
**Pull request by baum**
write queue - filesystem notifications

Signed-off-by: Alexander Indenbaum <aindenba@redhat.com>

### CODE REVIEW

**Review by guymguym — COMMENTED** [review]
@baum I don't think the queue need any notifications from the filesystem. We already get notifications from the api and can handle those if needed, but ultimately it's a simple folder that should get emptied asap.

**Comment by guymguym** [comment]
We might want fsnotify for the sync folder feature, but its going to be challenging to consume the fs notifications without missing events, and make sure we always find the items to sync eventually.

So instead of starting with a PR I would start from a design doc.

**Comment by baum** [comment]
Does [that sleep](https://github.com/s3d-rs/s3d/blob/a3ac2b548f5a612a58524332d2ecb9be5d08cc34/src/write_queue.rs#L23) help the folder to get emptied asap? 😀

An event-driven approach seems more elegant, WDYT?

**Comment by guymguym** [comment]
The sleep only occurs when the folder is empty

**Comment by guymguym** [comment]
I dont think so - a queue like that has no need for such event driven from its underlying fs storage.

**Comment by baum** [comment]
See [the loop]( https://github.com/s3d-rs/s3d/blob/a3ac2b548f5a612a58524332d2ecb9be5d08cc34/src/write_queue.rs#L22-L27)...
```
loop {
  sleep;
  work;
}
```

IMHO the sleep is in a loop before each work iteration. Would not it be beneficial to remove it? 😸

**Comment by guymguym** [comment]
No...

**Comment by guymguym** [comment]
The work function consumes the entire queue and then the worker takes a break.

**Comment by guymguym** [comment]
Hi @baum apologies for my short replies over the weekend, I wasn't able to take enough time to explain, but still preferred to let you know faster-than-later so you can avoid redundant work. It would be great to get heads up when you plan on working on some feature.

I will start a design doc this week for the write queue feature and explain the directions and considerations, and then we can discuss further.

Thanks for taking a stab at rust and fsnotify! I am sure that this example will be helpful for the sync folder feature, once we get to design it. 🙏🖖

**Pull request closed without merging**
